# Handling Imbalanced Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url = 'https://www.kaggle.com/mlg-ulb/creditcardfraud?select=creditcard.csv'
df = pd.read_csv(url)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2


In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [8]:
print(df.isnull().sum())
print("\n---\n")
print(df.isnull().count())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

---

Time      284807
V1        284807
V2        284807
V3        284807
V4        284807
V5        284807
V6        284807
V7        284807
V8        284807
V9        284807
V10       284807
V11       284807
V12       284807
V13       284807
V14       284807
V15       284807
V16       284807
V17       284807
V18       284807
V19       284807
V20       284807
V21       284807
V22       284807
V23       284807
V24       284807
V25       284807
V26       284807
V27       284807
V28       284807
Amount    284807
Class     284807
dtype: int64


In [14]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [15]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [16]:
# X will be Independent Feature
X = df.drop(['Class'],axis=1)

# Y will be Dependent Feature
Y = df.Class

### Cross Validation like KFold and Hyperparameter tuning

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold,GridSearchCV,train_test_split

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.7)

In [23]:
10.0 ** np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [24]:
log_class = LogisticRegression()
grid = {'C':10.0 ** np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5, shuffle=False, random_state=None)

In [31]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(X_train,Y_train)

C:\Users\stewa\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [32]:
Y_pred = clf.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85256    29]
 [   51   107]]
0.9990637032875719
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.79      0.68      0.73       158

    accuracy                           1.00     85443
   macro avg       0.89      0.84      0.86     85443
weighted avg       1.00      1.00      1.00     85443



In [33]:
from sklearn.ensemble import RandomForestClassifier

# without giving any class weight
classifier = RandomForestClassifier()
classifier.fit(X_train,Y_train)

RandomForestClassifier()

In [34]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85275    10]
 [   35   123]]
0.9994733330992591
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.92      0.78      0.85       158

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [38]:
print(X_train.shape)
Y_train.value_counts()

(199364, 30)


0    199030
1       334
Name: Class, dtype: int64

In [39]:
class_weight = dict({0:1,1:100})

In [40]:
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,Y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [41]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85276     9]
 [   37   121]]
0.9994616293903538
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.93      0.77      0.84       158

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



### Under Sampling

In [45]:
from collections import Counter
print(Y_train.value_counts())
print(Counter(Y_train))

0    199030
1       334
Name: Class, dtype: int64
Counter({0: 199030, 1: 334})


In [53]:
from imblearn.under_sampling import NearMiss
ns= NearMiss(0.75)

X_train_ns, Y_train_ns = ns.fit_sample(X_train, Y_train)
print("Number of class before Fit {}".format(Counter(Y_train)))
print("Number of class after Fit {}".format(Counter(Y_train_ns)))

C:\Users\stewa\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


Number of class before Fit Counter({0: 199030, 1: 334})
Number of class after Fit Counter({0: 445, 1: 334})


In [54]:
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,Y_train_ns)

RandomForestClassifier()

In [55]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[77923  7362]
 [   16   142]]
0.9136500356963122
              precision    recall  f1-score   support

           0       1.00      0.91      0.95     85285
           1       0.02      0.90      0.04       158

    accuracy                           0.91     85443
   macro avg       0.51      0.91      0.50     85443
weighted avg       1.00      0.91      0.95     85443



### Over Sampling

In [56]:
from imblearn.over_sampling import RandomOverSampler

In [62]:
os = RandomOverSampler(0.75)

X_train_os, Y_train_os = os.fit_sample(X_train, Y_train)
print("Number of class before Fit {}".format(Counter(Y_train)))
print("Number of class after Fit {}".format(Counter(Y_train_os)))

C:\Users\stewa\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


Number of class before Fit Counter({0: 199030, 1: 334})
Number of class after Fit Counter({0: 199030, 1: 149272})


In [63]:
classifier = RandomForestClassifier()
classifier.fit(X_train_os,Y_train_os)

RandomForestClassifier()

In [64]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85273    12]
 [   34   124]]
0.9994616293903538
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.91      0.78      0.84       158

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



### SMOTETomek

In [66]:
from imblearn.combine import SMOTETomek

In [68]:
smote = SMOTETomek(0.75)

X_train_sm, Y_train_sm = smote.fit_sample(X_train, Y_train)
print("Number of class before Fit {}".format(Counter(Y_train)))
print("Number of class after Fit {}".format(Counter(Y_train_sm)))

C:\Users\stewa\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


Number of class before Fit Counter({0: 199030, 1: 334})
Number of class after Fit Counter({0: 198381, 1: 148623})


In [69]:
classifier = RandomForestClassifier()
classifier.fit(X_train_sm,Y_train_sm)

RandomForestClassifier()

In [70]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85263    22]
 [   31   127]]
0.9993797034280163
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.85      0.80      0.83       158

    accuracy                           1.00     85443
   macro avg       0.93      0.90      0.91     85443
weighted avg       1.00      1.00      1.00     85443



### Ensemble Technique

In [71]:
from imblearn.ensemble import EasyEnsembleClassifier

In [73]:
easy = EasyEnsembleClassifier()
easy.fit(X_train,Y_train)

EasyEnsembleClassifier()

In [74]:
Y_pred = easy.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[82484  2801]
 [   16   142]]
0.9670306520136231
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85285
           1       0.05      0.90      0.09       158

    accuracy                           0.97     85443
   macro avg       0.52      0.93      0.54     85443
weighted avg       1.00      0.97      0.98     85443

